### PR TITLE
Changes to Go-compiler to use "txn" for using transactions

### PR DESCRIPTION
**Pull request by mohit10verma**
Includes all the changes to-date (including the ability to use sync.(*RWMutex).Lock & Unlock & carry transactions across function calls).
All changes are fully functional only for undo transactions.
The changes have some TODOs marked with TODO: (mohitv) which I plan to improve as we progress.

### CODE REVIEW

**Comment by pratapsu** [comment]
Hi Jerrin:

The go-pmem repository is also complaining that I don't have "write"
access. Can you tell me what I need to do?

Pratap

**Comment by jerrinsg** [comment]
> Hi Jerrin: The go-pmem repository is also complaining that I don't have "write" access. Can you tell me what I need to do? Pratap
> […](#)

I have added you as a 'collaborator' of go-pmem. Hopefully you should have write access once you accept the invitation.

**Comment by pratapsu** [comment]
Thanks, that fixed it.

**Comment by mohit10verma** [comment]
Closing this pull request, as it is difficult to review. I'll be passing along new small, logical chunks out of these commits as separate pull requests.

**Pull request closed without merging**
