### PR TITLE
Run GC in a new goroutine during initialization

### PR DESCRIPTION
**Pull request by jerrinsg**
This commit changes GC to be run in a new goroutine rather than as a stop the world (STW) event. This significantly speeds up the re-initialization function.

Earlier, GC was run as a stop-the-world event and initialization was declared to be complete only after the complete execution of GC. Now, initialization completes as soon as GC is started in a separate goroutine.

To compare impact of running garbage collection in a new goroutine vs as a STW event, I measured the memtier benchmark throughput in the two cases. The below graph shows the throughput while running memtier benchmark against Go Redis in two cases - (i) when GC is run in a new goroutine (ii) when GC is run as a STW event. The throughput of memtier benchmark is measured in kilo-operations per second. It is seen that, up to 700 milliseconds, the throughput in case (i) is pretty low. From 750 milliseconds onwards, the throughput picks up and is seen to be similar in the two cases.

image

### Memtier benchmark configuration
Num. clients = 10
Num threads = 10
Num. pipeline requests = 100
Num. requests = 1000000

### Initialization Time Comparison

Initialization time was compared in the two cases using Go Redis and memtier benchmark. About 2.6M Key value pairs were inserted into Go redis and the heap load time measured. The total database size was 1.28GB. More than 10x speedup was observed. No pointer swizzling was done in the two cases.

GC run as STW - 3.53 s
GC run in a new goroutine - 270.62 ms

### CODE REVIEW

**Comment by jerrinsg** [comment]
I re-ran the experiments with automatic garbage collection disabled after persistent memory initialization is complete and one full GC cycle is run. The below graph captures the throughput in this scenario.

image

With automatic GC disabled, it can be seen that when GC is run in a new goroutine, the throughput is initially low. It finally catches up with the throughput of the STW GC case when the garbage collection cycle completes execution.

It takes about 2.1 seconds for the throughput to catch up. This time depends on the amount of heap data. For this run, 4.5M KV pairs were inserted into Go Redis for a total database size of 2.23 GB.

### Initialization Time Comparison

STW -  5.46 seconds
Parallel - 544.75 ms

In both cases no pointer swizzling was done. But the swizzling code goes through the entire heap data and zeroes any pointers found that point outside the persistent heap.

**Comment by pratapsu** [comment]
When automatic garbage collection is ENABLED the throughput is initially lower, and then catches up. So far all is good. What is puzzling to me, is that the throughput diverges again, instead of tracing each other. What do you think is the reason for the divergence?

Second, when automatic garbage collection is DISABLED, the throughput takes about 2min to catch up. This is longer than when automatic garbage collection is enabled, this makes sense. It also makes sense that the two track each other almost perfectly for the remainder of the run. 

So, all my questions are when automatic garbage collection is enabled.

**Comment by jerrinsg** [comment]
The earlier two graphs were not entirely accurate as it shows the throughput of the two cases from the point memtier benchmark is able to insert KV pairs into the DB. But on an absolute time scale, with STW GC, memtier benchmark is able to insert KV pairs only after the completion of the GC cycle, whereas when GC is run in parallel, it can insert KV pairs as soon as GC is started. The below graph captures this better.

Picture1

This graph captures the throughput for the two cases observed over a period of more than 10 seconds. Memtier benchmark reports throughput once every 50ms. This is why the graph is not a smooth curve.
When GC is run in parallel, initialization takes about 580ms. When GC is run as STW, it takes 2.6 seconds. For this run 4.5M KV pairs were inserted in to the database for a total DB size of 2.23GB.

The circled regions on the graph indicate the approximate time at which garbage collection is triggered. It can be seen that throughput goes down when garbage collection happens in the background. This is because the user threads compete for CPU with the GC threads. The two cases don't trace each other as GC is started during different points in time in the two cases.

**Comment by jerrinsg** [comment]
Once the first GC cycle is completed, the behavior of the parallel GC curve is similar to that of STW GC curve. This can be verified by right shifting the parallel GC curve so that the circled GC points coincide with each other.

**Pull request merged**
